const METAFORCE_SERVICE_URL_REQUEST_CODE = "/metaforce/verification-code/request";
const METAFORCE_SERVICE_URL_VERIFY_CODE = "/metaforce/verification-code/verify";

const METAFORCE_SERVICE_URL_CUSTOMER = "/metaforce/customer";
const METAFORCE_SERVICE_URL_CASE = "/metaforce/case";
const METAFORCE_SERVICE_URL_CUSTOMER_RELATED_LIST = "/metaforce/customer-related-list";

const METAFORCE_PADDLE_URL_SUBSCRIPTION_CANCEL = "/paddle/subscription/cancel";


export {

    METAFORCE_SERVICE_URL_REQUEST_CODE,
    METAFORCE_SERVICE_URL_VERIFY_CODE,

    METAFORCE_SERVICE_URL_CUSTOMER,
    METAFORCE_SERVICE_URL_CASE,
    METAFORCE_SERVICE_URL_CUSTOMER_RELATED_LIST,

    METAFORCE_PADDLE_URL_SUBSCRIPTION_CANCEL
}